insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (1, 'Associate Professor', 'Media Manager III', 85, 1);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (2, 'Business Systems Development Analyst', 'Environmental Specialist', 24, 2);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (3, 'Safety Technician I', 'Quality Control Specialist', 63, 3);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (4, 'Marketing Assistant', 'Help Desk Operator', 51, 4);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (5, 'Financial Analyst', 'Research Nurse', 68, 5);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (6, 'Administrative Assistant II', 'Dental Hygienist', 84, 6);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (7, 'Assistant Professor', 'Data Coordiator', 85, 7);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (8, 'Senior Cost Accountant', 'Database Administrator I', 83, 8);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (9, 'Assistant Professor', 'Social Worker', 87, 9);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (10, 'Product Engineer', 'Account Executive', 70, 10);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (11, 'Nuclear Power Engineer', 'Human Resources Assistant II', 59, 11);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (12, 'Assistant Professor', 'Quality Engineer', 9, 12);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (13, 'Geologist I', 'Chemical Engineer', 25, 13);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (14, 'Data Coordiator', 'Senior Cost Accountant', 65, 14);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (15, 'General Manager', 'Internal Auditor', 8, 15);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (16, 'Social Worker', 'Media Manager II', 67, 16);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (17, 'General Manager', 'Director of Sales', 60, 17);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (18, 'Human Resources Manager', 'Product Engineer', 95, 18);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (19, 'Internal Auditor', 'Media Manager I', 47, 19);
insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (20, 'Associate Professor', 'Software Consultant', 8, 20);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (21, 'Design Engineer', 'Account Coordinator', 68, 21);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (22, 'Junior Executive', 'Mechanical Systems Engineer', 10, 22);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (23, 'Paralegal', 'Technical Writer', 50, 23);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (24, 'Statistician III', 'Mechanical Systems Engineer', 83, 24);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (25, 'Web Designer II', 'Human Resources Assistant III', 70, 25);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (26, 'Administrative Assistant III', 'Accounting Assistant III', 96, 26);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (27, 'Software Engineer III', 'Research Associate', 49, 27);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (28, 'Quality Control Specialist', 'Geological Engineer', 50, 28);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (29, 'Cost Accountant', 'Clinical Specialist', 90, 29);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (30, 'Financial Advisor', 'Payment Adjustment Coordinator', 48, 30);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (31, 'Payment Adjustment Coordinator', 'Tax Accountant', 73, 31);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (32, 'Technical Writer', 'Teacher', 45, 32);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (33, 'Web Developer II', 'Health Coach IV', 22, 33);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (34, 'VP Product Management', 'Account Representative I', 69, 34);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (35, 'Quality Control Specialist', 'VP Sales', 86, 35);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (36, 'Community Outreach Specialist', 'Registered Nurse', 72, 36);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (37, 'Compensation Analyst', 'VP Accounting', 90, 37);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (38, 'VP Quality Control', 'Payment Adjustment Coordinator', 99, 38);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (39, 'Geologist II', 'Chief Design Engineer', 99, 39);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (40, 'VP Quality Control', 'Account Coordinator', 100, 40);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (41, 'Assistant Manager', 'Payment Adjustment Coordinator', 39, 41);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (42, 'Account Coordinator', 'Help Desk Operator', 4, 42);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (43, 'Recruiting Manager', 'Librarian', 15, 43);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (44, 'VP Quality Control', 'Design Engineer', 46, 44);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (45, 'Account Coordinator', 'Office Assistant III', 64, 45);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (46, 'Human Resources Manager', 'Senior Financial Analyst', 47, 46);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (47, 'Registered Nurse', 'VP Quality Control', 49, 47);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (48, 'Web Developer I', 'Information Systems Manager', 80, 48);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (49, 'Librarian', 'Community Outreach Specialist', 84, 49);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (50, 'Assistant Media Planner', 'Technical Writer', 43, 50);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (51, 'Design Engineer', 'Editor', 20, 51);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (52, 'Desktop Support Technician', 'Help Desk Operator', 71, 52);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (53, 'Operator', 'Data Coordiator', 66, 53);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (54, 'Assistant Professor', 'Social Worker', 1, 54);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (55, 'Mechanical Systems Engineer', 'Media Manager IV', 97, 55);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (56, 'Account Coordinator', 'Marketing Assistant', 99, 56);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (57, 'Senior Developer', 'Senior Quality Engineer', 100, 57);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (58, 'Information Systems Manager', 'Chief Design Engineer', 32, 58);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (59, 'Software Engineer II', 'Software Consultant', 36, 59);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (60, 'Media Manager I', 'Accounting Assistant I', 40, 60);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (61, 'Executive Secretary', 'Internal Auditor', 49, 61);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (62, 'Electrical Engineer', 'Senior Cost Accountant', 15, 62);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (63, 'Administrative Assistant II', 'Web Developer II', 19, 63);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (64, 'Paralegal', 'Research Associate', 90, 64);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (65, 'Financial Analyst', 'Legal Assistant', 32, 65);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (66, 'Quality Engineer', 'Software Test Engineer IV', 44, 66);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (67, 'Programmer I', 'Software Test Engineer II', 63, 67);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (68, 'VP Accounting', 'Account Representative II', 44, 68);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (69, 'Database Administrator IV', 'Administrative Assistant I', 85, 69);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (70, 'Budget/Accounting Analyst III', 'Engineer IV', 4, 70);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (71, 'Electrical Engineer', 'Health Coach III', 7, 71);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (72, 'Accounting Assistant I', 'Statistician II', 56, 72);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (73, 'Systems Administrator II', 'Environmental Specialist', 17, 73);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (74, 'GIS Technical Architect', 'Financial Analyst', 1, 74);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (75, 'Analog Circuit Design manager', 'Associate Professor', 83, 75);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (76, 'Administrative Officer', 'Environmental Specialist', 25, 76);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (77, 'Senior Cost Accountant', 'Associate Professor', 46, 77);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (78, 'Biostatistician III', 'Human Resources Manager', 20, 78);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (79, 'Analog Circuit Design manager', 'Analog Circuit Design manager', 61, 79);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (80, 'Sales Associate', 'Marketing Assistant', 97, 80);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (81, 'Compensation Analyst', 'Senior Developer', 59, 81);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (82, 'Senior Sales Associate', 'Programmer II', 89, 82);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (83, 'Senior Cost Accountant', 'Automation Specialist I', 72, 83);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (84, 'Operator', 'Web Developer IV', 41, 84);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (85, 'Accounting Assistant IV', 'Social Worker', 14, 85);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (86, 'Nurse Practicioner', 'Quality Control Specialist', 74, 86);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (87, 'Software Engineer II', 'Design Engineer', 66, 87);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (88, 'Programmer IV', 'Office Assistant III', 10, 88);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (89, 'Engineer I', 'Marketing Manager', 12, 89);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (90, 'Environmental Specialist', 'Paralegal', 7, 90);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (91, 'Account Executive', 'Office Assistant III', 14, 91);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (92, 'Account Executive', 'Assistant Professor', 1, 92);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (93, 'Pharmacist', 'Web Designer IV', 64, 93);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (94, 'Structural Engineer', 'Business Systems Development Analyst', 61, 94);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (95, 'Engineer III', 'VP Quality Control', 11, 95);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (96, 'Staff Accountant IV', 'Software Consultant', 93, 96);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (97, 'Biostatistician II', 'Human Resources Manager', 84, 97);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (98, 'Internal Auditor', 'Information Systems Manager', 9, 98);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (99, 'Software Consultant', 'Automation Specialist I', 57, 99);
-- insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values (100, 'Computer Systems Analyst I', 'Executive Secretary', 42, 100);
