insert into empleados (id_Empleado, Profesion, Tipo_Cargo, Tiempo_Nomina, id_Personas) values 
(1, 'Associate Professor', 'Media Manager III', 85, 1),
(2, 'Business Systems Development Analyst', 'Environmental Specialist', 24, 2),
(3, 'Safety Technician I', 'Quality Control Specialist', 63, 3),
(4, 'Marketing Assistant', 'Help Desk Operator', 51, 4),
(5, 'Financial Analyst', 'Research Nurse', 68, 5),
(6, 'Administrative Assistant II', 'Dental Hygienist', 84, 6),
(7, 'Assistant Professor', 'Data Coordiator', 85, 7),
(8, 'Senior Cost Accountant', 'Database Administrator I', 83, 8),
(9, 'Assistant Professor', 'Social Worker', 87, 9),
(10, 'Product Engineer', 'Account Executive', 70, 10),
(11, 'Nuclear Power Engineer', 'Human Resources Assistant II', 59, 11),
(12, 'Assistant Professor', 'Quality Engineer', 9, 12),
(13, 'Geologist I', 'Chemical Engineer', 25, 13),
(14, 'Data Coordiator', 'Senior Cost Accountant', 65, 14),
(15, 'General Manager', 'Internal Auditor', 8, 15),
(16, 'Social Worker', 'Media Manager II', 67, 16),
(17, 'General Manager', 'Director of Sales', 60, 17),
(18, 'Human Resources Manager', 'Product Engineer', 95, 18),
(19, 'Internal Auditor', 'Media Manager I', 47, 19),
(20, 'Associate Professor', 'Software Consultant', 8, 20);